import type { CopyDictionary } from './types'

const copy: Record<string, CopyDictionary> = {
  en: {
    common: {
      loadingUserName: 'Developer',
      serverError: 'A server error occurred.',
      routeLoadError: 'Unable to load route data.',
      saveError: 'Something went wrong while saving your selection.',
      saveSuccess: 'Your stop has been saved.',
      openInGoogleMaps: 'Open in Google Maps',
      rideAt: 'Board at',
      stopNumber: 'Stop',
      line: 'LINE',
    },
    tabs: {
      home: 'Home',
      stops: 'Stops',
      scan: 'Scan',
      notifications: 'Alerts',
      settings: 'Settings',
    },
    home: {
      noRegistration: 'No registered stop was found. Please choose your stop first.',
      findStop: 'Find a Stop',
      later: 'Later',
      qrComingSoon: 'QR scanning will be available soon.',
      scanQr: 'Scan QR Code',
      changeStop: 'Change Stop',
      panelTitle: 'Shuttle Routes',
      panelHint: 'Browse every route, or jump straight into your saved stop.',
      routeDetailBack: 'Routes',
      routeDetailHint: 'Preview every stop and boarding time on this route.',
      registeredRouteTitle: 'Your registered route',
      registeredRouteHint: 'This route is selected automatically when you open the page.',
      selectedStopLabel: 'Selected stop',
      browseRoutesTitle: 'Browse routes',
      browseRoutesHint: 'Tap a route to preview every stop and boarding time.',
      viewStopDetails: 'View Stop Details',
      viewRouteMap: 'Open Route Map',
      noRoutes: 'No active routes are available right now.',
      routesHeader: 'Routes',
      myRouteHeader: 'My Route',
      moreHeader: 'More',
      stopCount: 'stops',
      requestStop: 'Request a Stop',
      clearSelection: 'Reset',
      stationDetail: 'Detail',
      selected: 'Selected',
      settings: 'Settings',
      selectedBadge: 'Selected',
      footerLabel: 'NaNum and SeomKim Church',
      footerContent:
        'KPC(SINGAPORE) LTD. 12 Shelford Road Singapore 288370 Tel 65-6467-4476 / Fax 65-6469-3175 / E-mail nasumchurch@gmail.com Copyright (c) Korean Presbyterian Church All Right Reserved.',
      profileAriaLabel: 'Open settings',
      zoomInAriaLabel: 'Zoom in',
      zoomOutAriaLabel: 'Zoom out',
      currentLocationAriaLabel: 'Move to my current location',
      currentLocationUnavailable: 'Unable to access your location.',
    },
    scan: {
      title: 'QR Check-in',
      description: 'QR scanning will be available soon. We will connect this tab to check-in once the flow is ready.',
    },
    notifications: {
      title: 'Chat Alerts',
      description: 'This tab will list shuttle and chat-related alerts in one place.',
    },
    settings: {
      title: 'Settings',
      profileHeader: 'Profile',
      routeHeader: 'Route',
      preferencesHeader: 'Preferences',
      themeHeader: 'Theme Settings',
      versionHeader: 'Version Info',
      displayName: 'Display Name',
      userId: 'User ID',
      currentRoute: 'Current Route',
      currentStop: 'Current Stop',
      noRouteSelected: 'No route selected yet',
      changeRoute: 'Change Stop / Route',
      pushNotifications: 'Push Notifications',
      pushNotificationsHint: 'Receive updates about shuttle timing and route changes on this device',
      language: 'Language',
      languageEnglish: 'English',
      languageKorean: 'Korean',
      darkMode: 'Dark Mode',
      antdMobileVersion: 'antd-mobile',
      liffSdkVersion: 'LIFF SDK',
      lineVersion: 'LINE',
    },
    search: {
      title: 'Search Stops',
      list: 'List',
      registerButton: 'Register This Stop',
      searchPlaceholder: 'Search stops',
      alphabetical: 'A-Z',
      distance: 'Nearby',
      distanceUnavailable: 'Location unavailable. Showing A-Z order instead.',
      map: 'Map',
      mapTitle: 'Stop Map',
      mapHint: 'Tap a marker to open that stop.',
    },
    stopDetail: {
      title: 'Stop Details',
      chooseRoute: 'Choose the route for this stop',
      chooseRouteSectionTitle: 'Available routes',
      chooseRouteSectionHint: 'Choose the route and boarding time for this stop.',
      noResults: 'No matching stop details were found.',
      noSelection: 'Choose route and time.',
      registerButton: 'Register Stop',
      routeMap: 'Route map',
      stopMap: 'Stop location',
      stopPreview: 'Stop location preview',
      notes: 'Notes',
      route: 'Route',
      stopOrder: 'Stop',
      boardAt: 'Board at',
    },
  },
  ko: {
    common: {
      loadingUserName: '개발자',
      serverError: '서버 오류가 발생했습니다.',
      routeLoadError: '노선 정보를 불러올 수 없습니다.',
      saveError: '선택 정보를 저장하는 중 문제가 발생했습니다.',
      saveSuccess: '정류장 정보가 저장되었습니다.',
      openInGoogleMaps: 'Google Maps에서 열기',
      rideAt: '탑승 시간',
      stopNumber: '정류장',
      line: 'LINE',
    },
    tabs: {
      home: '홈',
      stops: '정류장',
      scan: 'QR',
      notifications: '알림',
      settings: '설정',
    },
    home: {
      noRegistration: '등록된 정류장이 없습니다. 먼저 정류장을 선택해 주세요.',
      findStop: '정류장 찾기',
      later: '나중에',
      qrComingSoon: 'QR 스캔 기능은 곧 제공됩니다.',
      scanQr: 'QR 코드 스캔',
      changeStop: '정류장 변경',
      panelTitle: '셔틀 노선',
      panelHint: '전체 노선을 둘러보거나 저장한 정류장으로 바로 이동할 수 있습니다.',
      routeDetailBack: '노선',
      routeDetailHint: '선택한 노선의 전체 정류장과 탑승 시간을 확인하세요.',
      registeredRouteTitle: '내 등록 노선',
      registeredRouteHint: '페이지를 열면 이 노선이 자동으로 선택됩니다.',
      selectedStopLabel: '선택한 정류장',
      browseRoutesTitle: '노선 둘러보기',
      browseRoutesHint: '노선을 눌러 정류장과 탑승 시간을 확인하세요.',
      viewStopDetails: '정류장 상세 보기',
      viewRouteMap: '노선 지도 열기',
      noRoutes: '현재 이용 가능한 노선이 없습니다.',
      routesHeader: '노선',
      myRouteHeader: '내 노선',
      moreHeader: '더보기',
      stopCount: '정류장',
      requestStop: '정류장 요청',
      clearSelection: '초기화',
      stationDetail: '상세',
      selected: '선택됨',
      settings: '설정',
      selectedBadge: '선택됨',
      footerLabel: '나눔과섬김교회',
      footerContent:
        'KPC(SINGAPORE) LTD. 12 Shelford Road Singapore 288370 Tel 65-6467-4476 / Fax 65-6469-3175 / E-mail nasumchurch@gmail.com Copyright (c) Korean Presbyterian Church All Right Reserved.',
      profileAriaLabel: '설정 열기',
      zoomInAriaLabel: '지도 확대',
      zoomOutAriaLabel: '지도 축소',
      currentLocationAriaLabel: '현재 위치로 이동',
      currentLocationUnavailable: '현재 위치 정보를 사용할 수 없습니다.',
    },
    scan: {
      title: 'QR 체크인',
      description: 'QR 스캔 기능은 곧 제공됩니다. 체크인 흐름이 준비되면 이 탭에서 바로 사용할 수 있습니다.',
    },
    notifications: {
      title: '채팅 알림',
      description: '셔틀 관련 공지와 채팅 알림을 한 곳에서 볼 수 있도록 준비 중입니다.',
    },
    settings: {
      title: '설정',
      profileHeader: '프로필',
      routeHeader: '노선',
      preferencesHeader: '환경설정',
      themeHeader: '테마 설정',
      versionHeader: '버전 정보',
      displayName: '이름',
      userId: '사용자 ID',
      currentRoute: '현재 노선',
      currentStop: '현재 정류장',
      noRouteSelected: '아직 선택한 노선이 없습니다',
      changeRoute: '정류장 / 노선 변경',
      pushNotifications: '푸시 알림',
      pushNotificationsHint: '이 기기에서 셔틀 시간 및 노선 변경 알림을 받습니다',
      language: '언어',
      languageEnglish: '영어',
      languageKorean: '한국어',
      darkMode: '다크 모드',
      antdMobileVersion: 'antd-mobile',
      liffSdkVersion: 'LIFF SDK',
      lineVersion: 'LINE',
    },
    search: {
      title: '정류장 검색',
      list: '목록',
      registerButton: '이 정류장 등록',
      searchPlaceholder: '정류장 검색',
      alphabetical: 'A-Z',
      distance: '거리순',
      distanceUnavailable: '위치 정보를 사용할 수 없어 A-Z 순서로 표시합니다.',
      map: '지도',
      mapTitle: '정류장 지도',
      mapHint: '마커를 눌러 해당 정류장을 여세요.',
    },
    stopDetail: {
      title: '정류장 상세',
      chooseRoute: '이 정류장의 노선을 선택하세요',
      chooseRouteSectionTitle: '이용 가능한 노선',
      chooseRouteSectionHint: '이 정류장의 노선과 탑승 시간을 선택하세요.',
      noResults: '일치하는 정류장 상세 정보를 찾을 수 없습니다.',
      noSelection: '노선과 시간을 선택하세요.',
      registerButton: '정류장 등록',
      routeMap: '노선 지도',
      stopMap: '정류장 위치',
      stopPreview: '정류장 위치 미리보기',
      notes: '메모',
      route: '노선',
      stopOrder: '정류장',
      boardAt: '탑승 시간',
    },
  },
}

export function getCopy(locale = 'en'): CopyDictionary {
  return copy[locale] ?? copy.en
}
