import type { CopyDictionary } from './types'

const copy: Record<string, CopyDictionary> = {
  en: {
    common: {
      loadingUserName: 'Developer',
      serverError: 'A server error occurred.',
      routeLoadError: 'Unable to load route data.',
      saveError: 'Something went wrong while saving your selection.',
      saveSuccess: 'Your stop has been saved.',
      openInGoogleMaps: 'Open in Google Maps',
      rideAt: 'Board at',
      stopNumber: 'Stop',
      line: 'LINE',
    },
    home: {
      noRegistration: 'No registered stop was found. Please choose your stop first.',
      findStop: 'Find a Stop',
      later: 'Later',
      qrComingSoon: 'QR scanning will be available soon.',
      scanQr: 'Scan QR Code',
      changeStop: 'Change Stop',
      panelTitle: 'Shuttle Routes',
      panelHint: 'Browse every route, or jump straight into your saved stop.',
      registeredRouteTitle: 'Your registered route',
      registeredRouteHint: 'This route is selected automatically when you open the page.',
      selectedStopLabel: 'Selected stop',
      browseRoutesTitle: 'Browse routes',
      browseRoutesHint: 'Tap a route to preview every stop and boarding time.',
      viewStopDetails: 'View Stop Details',
      viewRouteMap: 'Open Route Map',
      noRoutes: 'No active routes are available right now.',
      routesHeader: 'Routes',
      myRouteHeader: 'My Route',
      moreHeader: 'More',
      stopCount: 'stops',
      requestStop: 'Request a Stop',
      settings: 'Settings',
      selectedBadge: 'Selected',
      footerLabel: 'NaNum and SeomKim Church',
      footerContent:
        'KPC(SINGAPORE) LTD. 12 Shelford Road Singapore 288370 Tel 65-6467-4476 / Fax 65-6469-3175 / E-mail nasumchurch@gmail.com Copyright (c) Korean Presbyterian Church All Right Reserved.',
      profileAriaLabel: 'Open settings',
    },
    settings: {
      title: 'Settings',
      profileHeader: 'Profile',
      routeHeader: 'Route',
      preferencesHeader: 'Preferences',
      aboutHeader: 'About',
      displayName: 'Display Name',
      userId: 'User ID',
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      currentRoute: 'Current Route',
      currentStop: 'Current Stop',
      noRouteSelected: 'No route selected yet',
      changeRoute: 'Change Stop / Route',
      pushNotifications: 'Push Notifications',
      pushNotificationsHint: 'Receive updates about shuttle timing and route changes on this device',
    },
    search: {
      title: 'Register My Stop',
      registerButton: 'Register This Stop',
      searchPlaceholder: 'Search stops',
      alphabetical: 'A-Z',
      distance: 'Nearby',
      distanceUnavailable: 'Location unavailable. Showing A-Z order instead.',
      map: 'Map',
      mapTitle: 'Stop Map',
      mapHint: 'Tap a marker to open that stop.',
    },
    stopDetail: {
      title: 'Stop Details',
      chooseRoute: 'Choose the route for this stop',
      chooseRouteSectionTitle: 'Available routes',
      chooseRouteSectionHint: 'Choose the route and boarding time for this stop.',
      noResults: 'No matching stop details were found.',
      noSelection: 'Select the correct route and time for this stop.',
      registerButton: 'Register Stop',
      routeMap: 'Route map',
      stopMap: 'Stop location',
      stopPreview: 'Stop location preview',
      notes: 'Notes',
      route: 'Route',
      stopOrder: 'Stop',
      boardAt: 'Board at',
    },
  },
}

export function getCopy(locale = 'en'): CopyDictionary {
  return copy[locale] ?? copy.en
}
