import type { AppNotification } from '@app-types/core';

const t = (offsetMs: number) => new Date(Date.now() - offsetMs).toISOString();
const min = 60_000;
const hr = 60 * min;
const day = 24 * hr;

export const DEV_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'd1',
    run_id: 'run-20260405-L1',
    trigger_stop_id: 'rs-l1-03',
    stops_away: 1,
    is_read: false,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-04',
    title_ko: '탑승을 준비하세요',
    body_ko: '셔틀버스가 바로 전 정류장에 도착했습니다. 탑승을 준비하세요.',
    title_en: 'Get ready to board',
    body_en:
      'The shuttle has arrived at the previous stop. Get ready to board.',
    created_at: t(3 * min),
  },
  {
    id: 'd2',
    run_id: 'run-20260405-L1',
    trigger_stop_id: 'rs-l1-02',
    stops_away: 2,
    is_read: false,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-04',
    title_ko: '셔틀 탑승 준비',
    body_ko: '셔틀버스가 두 정류장 전에 도착했습니다.',
    title_en: 'Prepare to board',
    body_en: 'The shuttle is 2 stops away.',
    created_at: t(20 * min),
  },
  {
    id: 'd3',
    run_id: 'run-20260404-L1',
    trigger_stop_id: 'rs-l1-05',
    stops_away: 1,
    is_read: true,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-06',
    title_ko: '탑승을 준비하세요',
    body_ko: '셔틀버스가 바로 전 정류장에 도착했습니다. 탑승을 준비하세요.',
    title_en: 'Get ready to board',
    body_en:
      'The shuttle has arrived at the previous stop. Get ready to board.',
    created_at: t(2 * day),
  },
  {
    id: 'd4',
    run_id: 'run-20260404-L2',
    trigger_stop_id: 'rs-l2-02',
    stops_away: 2,
    is_read: true,
    route_code: 'L2',
    user_route_stop_id: 'rs-l2-04',
    title_ko: '셔틀 탑승 준비',
    body_ko: '셔틀버스가 두 정류장 전에 도착했습니다.',
    title_en: 'Prepare to board',
    body_en: 'The shuttle is 2 stops away.',
    created_at: t(7 * day),
  },
  {
    id: 'd5',
    run_id: 'run-20260404-L2',
    trigger_stop_id: 'rs-l2-01',
    stops_away: 1,
    is_read: true,
    route_code: 'L2',
    user_route_stop_id: 'rs-l2-02',
    title_ko: '탑승을 준비하세요',
    body_ko: '셔틀버스가 바로 전 정류장에 도착했습니다. 탑승을 준비하세요.',
    title_en: 'Get ready to board',
    body_en:
      'The shuttle has arrived at the previous stop. Get ready to board.',
    created_at: t(8 * day),
  },
  {
    id: 'd6',
    run_id: 'run-20260403-L1',
    trigger_stop_id: 'rs-l1-03',
    stops_away: 2,
    is_read: true,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-05',
    title_ko: '셔틀 탑승 준비',
    body_ko: '셔틀버스가 두 정류장 전에 도착했습니다.',
    title_en: 'Prepare to board',
    body_en: 'The shuttle is 2 stops away.',
    created_at: t(9 * day),
  },
  {
    id: 'd7',
    run_id: 'run-20260403-L1',
    trigger_stop_id: 'rs-l1-02',
    stops_away: 1,
    is_read: true,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-03',
    title_ko: '탑승을 준비하세요',
    body_ko: '셔틀버스가 바로 전 정류장에 도착했습니다. 탑승을 준비하세요.',
    title_en: 'Get ready to board',
    body_en:
      'The shuttle has arrived at the previous stop. Get ready to board.',
    created_at: t(14 * day),
  },
  {
    id: 'd8',
    run_id: 'run-20260330-L2',
    trigger_stop_id: 'rs-l2-03',
    stops_away: 2,
    is_read: true,
    route_code: 'L2',
    user_route_stop_id: 'rs-l2-05',
    title_ko: '셔틀 탑승 준비',
    body_ko: '셔틀버스가 두 정류장 전에 도착했습니다.',
    title_en: 'Prepare to board',
    body_en: 'The shuttle is 2 stops away.',
    created_at: t(15 * day),
  },
  {
    id: 'd9',
    run_id: 'run-20260330-L2',
    trigger_stop_id: 'rs-l2-02',
    stops_away: 1,
    is_read: true,
    route_code: 'L2',
    user_route_stop_id: 'rs-l2-03',
    title_ko: '탑승을 준비하세요',
    body_ko: '셔틀버스가 바로 전 정류장에 도착했습니다. 탑승을 준비하세요.',
    title_en: 'Get ready to board',
    body_en:
      'The shuttle has arrived at the previous stop. Get ready to board.',
    created_at: t(21 * day),
  },
  {
    id: 'd10',
    run_id: 'run-20260323-L1',
    trigger_stop_id: 'rs-l1-04',
    stops_away: 2,
    is_read: true,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-06',
    title_ko: '셔틀 탑승 준비',
    body_ko: '셔틀버스가 두 정류장 전에 도착했습니다.',
    title_en: 'Prepare to board',
    body_en: 'The shuttle is 2 stops away.',
    created_at: t(28 * day),
  },
  {
    id: 'd11',
    run_id: 'run-20260323-L1',
    trigger_stop_id: 'rs-l1-03',
    stops_away: 1,
    is_read: true,
    route_code: 'L1',
    user_route_stop_id: 'rs-l1-04',
    title_ko: '탑승을 준비하세요',
    body_ko: '셔틀버스가 바로 전 정류장에 도착했습니다. 탑승을 준비하세요.',
    title_en: 'Get ready to board',
    body_en:
      'The shuttle has arrived at the previous stop. Get ready to board.',
    created_at: t(29 * day),
  },
  {
    id: 'd12',
    run_id: 'run-20260316-L2',
    trigger_stop_id: 'rs-l2-01',
    stops_away: 2,
    is_read: true,
    route_code: 'L2',
    user_route_stop_id: 'rs-l2-03',
    title_ko: '셔틀 탑승 준비',
    body_ko: '셔틀버스가 두 정류장 전에 도착했습니다.',
    title_en: 'Prepare to board',
    body_en: 'The shuttle is 2 stops away.',
    created_at: t(35 * day),
  },
];
